# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'inicial.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import teste_rc
import logosoft_rc
import iconeprogram_rc

class Ui_AppDownloader(object):
    def setupUi(self, AppDownloader):
        if not AppDownloader.objectName():
            AppDownloader.setObjectName(u"AppDownloader")
        AppDownloader.resize(722, 500)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AppDownloader.sizePolicy().hasHeightForWidth())
        AppDownloader.setSizePolicy(sizePolicy)
        AppDownloader.setMinimumSize(QSize(722, 500))
        AppDownloader.setMaximumSize(QSize(722, 500))
        AppDownloader.setSizeIncrement(QSize(722, 500))
        icon = QIcon()
        icon.addPixmap(QPixmap(corpng.(u":/newPrefix/icone.png")), QIcon.Normal, QIcon.Off)
        icon.addPixmap(QPixmap(corpng.(u"icone.png")), QIcon.Normal, QIcon.On)
        icon.addPixmap(QPixmap(corpng.(u"icone.png")), QIcon.Disabled, QIcon.Off)
        icon.addPixmap(QPixmap(corpng.(u"icone.png")), QIcon.Disabled, QIcon.On)
        icon.addPixmap(QPixmap(corpng.(u":/newPrefix/icone.png")), QIcon.Active, QIcon.Off)
        icon.addPixmap(QPixmap(corpng.(u"icone.png")), QIcon.Active, QIcon.On)
        icon.addPixmap(QPixmap(corpng.(u"icone.png")), QIcon.Selected, QIcon.Off)
        icon.addPixmap(QPixmap(corpng.(u"icone.png")), QIcon.Selected, QIcon.On)
        AppDownloader.setWindowIcon(icon)
        AppDownloader.setStyleSheet(u"background-color: rgb(25, 25, 25);\n"
"background-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.centralwidget = QWidget(AppDownloader)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setEnabled(True)
        sizePolicy1 = QSizePolicy(QSizePolicy.Maximum, QSizePolicy.Ignored)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy1)
        self.centralwidget.setMinimumSize(QSize(722, 479))
        self.centralwidget.setMaximumSize(QSize(722, 749))
        self.centralwidget.setLayoutDirection(Qt.LeftToRight)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 180, 141, 21))
        font = QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(610, 180, 101, 21))
        self.pushButton.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(30, 250, 161, 61))
        font1 = QFont()
        font1.setPointSize(10)
        font1.setBold(True)
        font1.setItalic(True)
        font1.setUnderline(False)
        font1.setWeight(75)
        self.pushButton_2.setFont(font1)
        self.pushButton_2.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_2.setMouseTracking(False)
        self.pushButton_2.setAcceptDrops(False)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet(u"background-color: rgb(236, 0, 0);")
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setAutoExclusive(False)
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(270, 250, 161, 61))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(True)
        font2.setItalic(True)
        font2.setWeight(75)
        self.pushButton_3.setFont(font2)
        self.pushButton_3.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet(u"background-color: rgb(236, 0, 0);")
        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(500, 250, 161, 61))
        font3 = QFont()
        font3.setPointSize(10)
        font3.setBold(True)
        font3.setItalic(True)
        font3.setUnderline(False)
        font3.setWeight(75)
        font3.setStrikeOut(False)
        self.pushButton_4.setFont(font3)
        self.pushButton_4.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet(u"background-color: rgb(236, 0, 0);")
        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(160, 180, 411, 21))
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(600, 460, 91, 16))
        self.label_2.setFont(font2)
        self.label_2.setStyleSheet(u"background-color: rgb(25, 25, 25);\n"
"background-color: rgb(255, 255, 255);")
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(560, 440, 171, 21))
        font4 = QFont()
        font4.setFamily(u"MS Shell Dlg 2")
        font4.setPointSize(8)
        font4.setBold(False)
        font4.setItalic(False)
        font4.setWeight(9)
        self.label_3.setFont(font4)
        self.label_3.setStyleSheet(u"background-color: rgb(25, 25, 25);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.comboBox = QComboBox(self.centralwidget)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(10, 0, 141, 22))
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet(u"background-color: rgb(255, 8, 0);\n"
"background-color: rgb(85, 85, 85);\n"
"\n"
"background-color: rgb(156, 156, 156);")
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(690, 450, 31, 31))
        self.label_4.setPixmap(QPixmap(corpng.(u"logobandeira.png")))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 10, 1441, 851))
        self.label_5.setPixmap(QPixmap(corpng.(u"logonova.png")))
        self.label_5.setScaledContents(True)
        self.pushButton_5 = QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(630, 0, 75, 23))
        AppDownloader.setCentralWidget(self.centralwidget)
        self.label_5.raise_()
        self.comboBox.raise_()
        self.label.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.lineEdit.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.pushButton_5.raise_()
        self.menubar = QMenuBar(AppDownloader)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 722, 21))
        AppDownloader.setMenuBar(self.menubar)

        self.retranslateUi(AppDownloader)

        QMetaObject.connectSlotsByName(AppDownloader)
    # setupUi

    def retranslateUi(self, AppDownloader):
        AppDownloader.setWindowTitle(QCoreApplication.translate("AppDownloader", u"Gp TubeDownloader", None))
        self.label.setText(QCoreApplication.translate("AppDownloader", u"Informe a URL do video : ", None))
        self.pushButton.setText(QCoreApplication.translate("AppDownloader", u"Novo Download", None))
#if QT_CONFIG(statustip)
        self.pushButton_2.setStatusTip("")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.pushButton_2.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.pushButton_2.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.pushButton_2.setText(QCoreApplication.translate("AppDownloader", u"Baixar Video", None))
        self.pushButton_3.setText(QCoreApplication.translate("AppDownloader", u"Baixar Audio", None))
        self.pushButton_4.setText(QCoreApplication.translate("AppDownloader", u"Baixar Playlist", None))
        self.label_2.setText(QCoreApplication.translate("AppDownloader", u"<html><head/><body><p><span style=\" font-weight:600; font-style:italic; color:#ff0000;\">Vers\u00e3o 1.0</span></p></body></html>", None))
        self.label_3.setText(QCoreApplication.translate("AppDownloader", u"<html><head/><body><p><span style=\" font-weight:600; font-style:italic; color:#ff0000;\">Dev: Gustavo Pinheiro </span></p></body></html>", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("AppDownloader", u" Resolu\u00e7\u00e3o do Video", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("AppDownloader", u"360p", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("AppDownloader", u"480p", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("AppDownloader", u"720p", None))
        self.comboBox.setItemText(4, QCoreApplication.translate("AppDownloader", u"1080p", None))

        self.label_4.setText("")
        self.label_5.setText("")
        self.pushButton_5.setText(QCoreApplication.translate("AppDownloader", u"Sair", None))
    # retranslateUi

